dist: trusty
language: node_js
node_js:
- stable
cache:
  npm: true
  directories:
  - node_modules
  - ~/.cache
install:
- npm ci
before_script:
- npm install -g httpserver
- npm run custom-build
- cd dist && httpserver -p 8080 &
script:
- npx cypress run

