dist: trusty
language: node_js
node_js:
- stable
cache:
  npm: true
  directories:
  - node_modules
  - ~/.cache/Cypress/3.1.3/Cypress/Cypress
before_script:
- npm install -g httpserver
- npm run custom-build
- cd dist && httpserver -p 8080 &
script:
- npx cypress run

