dist: trusty
language: node_js
node_js:
- stable
- 0.4
- 0.6
install:
- npm ci
cache:
  directories:
  - node_modules
before_script:
- npm install -g httpserver
- npm run custom-build
- cd dist && httpserver -p 8080 &
script:
- npx cypress run

